name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          SERVICE_ROLE_KEY: ${{ secrets.SERVICE_ROLE_KEY }}

        run: npm run build --omit=dev

      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: /var/www/gopay-merchant/
          remote_host: ec2-52-220-83-4.ap-southeast-1.compute.amazonaws.com
          remote_user: ubuntu
          remote_key: '${{ secrets.SSH_PRIVATE_KEY }}'
      - name: restart pm2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ec2-52-220-83-4.ap-southeast-1.compute.amazonaws.com
          username: ubuntu
          key: '${{ secrets.SSH_PRIVATE_KEY }}'
          command_timeout: 30m
          script: |
            pm2 restart merchant
